version: '3'

name: honeypots

services:
  honeypots:
    container_name: honeypots
    build: .
    image: honeypots:latest
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command: python3 -m honeypots --setup all --options capture_commands | python3 load_mongodb.py
    volumes:
      - ./load_mongodb.py:/root/load_mongodb.py
    restart: always

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    volumes:
      - mongodb-config:/data/configdb
    restart: always

  metabase:
    container_name: metabase
    image: metabase/metabase:latest
    ports:
      - 3000:3000
    restart: always
